# Generated by Django 2.2.4 on 2023-12-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last',
        ),
    ]
