# Generated by Django 2.2.14 on 2023-12-31 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20231229_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=225)),
                ('full_name', models.CharField(max_length=225)),
                ('mobile_number', models.CharField(max_length=225)),
                ('PIN_code', models.CharField(max_length=225)),
                ('Apartment', models.CharField(max_length=225)),
                ('street', models.CharField(max_length=225)),
                ('landmark', models.CharField(max_length=225)),
                ('town', models.CharField(max_length=225)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='app1.User')),
            ],
        ),
    ]
