# Generated by Django 4.2.8 on 2024-01-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='successfully_placed_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.CharField(blank=True, max_length=255, null=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('items', models.ManyToManyField(related_name='successfully_placed_items_in_order', to='app1.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
