# Generated by Django 4.2.8 on 2024-01-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_items_for_user', to='app1.user'),
        ),
    ]
