# Generated by Django 4.2.8 on 2024-01-01 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_orderitem_user_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.address'),
        ),
        migrations.DeleteModel(
            name='successfully_placed_Order',
        ),
    ]
