# Generated by Django 4.2.8 on 2024-01-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_order_total_payed_amount_payment_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_payed_amount',
            field=models.FloatField(),
        ),
    ]
